name: marketplace
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  lottie: ^3.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  csv: ^5.1.1
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/lottie/